### ISSUE TITLE
angularjs definition installation via Nuget raises 100 errors

### ISSUE THREAD

**Issue by atomroflman** [DefinitelyTyped/tsd#121]
I've tried to install the package for Angularjs. Now I've about 100 compiler errors beacuse it can't compile angular.d.ts an the others in the typings folder.

How can I resolve the problem?
Thanks in advance.

**Comment by pieterwillaert** [comment]
what version of typescript do you use?it should be 1.4.*

Also it seems that IntelliJ IDEA has not implemented support for 1.4 yet
https://youtrack.jetbrains.com/issue/WEB-14151, that might be your problem too

**Comment by QuantumInformation** [comment]
So this wouldn't work in TS 1.0?

```json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "angular-material/angular-material.d.ts": {
      "commit": "84dfeeac378552c22297a5d555b1999a396d7e7c"
    },
    "angularjs/angular.d.ts": {
      "commit": "84dfeeac378552c22297a5d555b1999a396d7e7c"
    },
    "jquery/jquery.d.ts": {
      "commit": "84dfeeac378552c22297a5d555b1999a396d7e7c"
    }
  }
}
```
I'm getting loads of errors like:

`typings/jquery/jquery.d.ts(279,59): error TS1005: ',' expected.
`

**Comment by Diullei** [comment]
Hi @QuantumInformation as @pieterwillaert spoke, You need to use the latest typescript version. 1.4.1

**Comment by Diullei** [comment]
NOTE: The TS version used by DefinitelyTyped can be verified with the latest Travis-ci build. https://travis-ci.org/borisyankov/DefinitelyTyped#L132

**Comment by QuantumInformation** [comment]
thanks it works now

**Comment by Diullei** [comment]
@atomroflman can I close this issue? Are you still with the problem?

**Comment by somashekharsk** [comment]
@Diullei  I tried accessing the path given by you but no luck, getting "We couldn't find the repository 
borisyankov/DefinitelyTyped"  https://travis-ci.org/borisyankov/DefinitelyTyped#L132
